spring:
  application:
    name: AzureTask1045_Policy_RestAPI-1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: shree@123
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
server:
    port: 8087	